<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-08-11 14:58

$extensionPath = t3lib_extMgm::extPath('purge');
$extensionClassesPath = t3lib_extMgm::extPath('purge') . 'Classes/';
return array(
	'tx_purge_cachemgr' => $extensionClassesPath . 'Cachemgr.php',
	'tx_purge_finder' => $extensionClassesPath . 'Finder.php',
	'tx_purge_locator' => $extensionClassesPath . 'Locator.php',
	'tx_purge_finder_realurl' => $extensionClassesPath . 'Finder/Realurl.php',
	'tx_purge_hooks_tcemain' => $extensionClassesPath . 'Hooks/Tcemain.php',
);
